### ISSUE TITLE
Login / Regsiter :

### ISSUE THREAD

**Issue by florianpdf** [WildCodeSchool/parisCode-1017-ozout#49]
- Quand on est déja logué, afficher notre nom à côté du profil dans la navbar ? OU autrement, mais on doit savoir qu'on est loggué. 
- Une fois loggué, on ne doit pas avoir accès à la page login / register
- Register : 
- Register /confirmed : retravailler le design => footer, image de fond

**Comment by varon27** [comment]
Register issues resolved.
Login issue relocated in Access Control issue.
